export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  USERS: '/users',
  USER_DETAIL: '/users/:id',
  REPORTS: '/reports',
  UI: '/ui',
  UI_COMPONENTS: '/ui/components',
  UI_ICONS: '/ui/icons',
  SETTINGS: '/settings',
  SETTINGS_APPEARANCE: '/settings/appearance',
  SETTINGS_PROFILE: '/settings/profile',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_ROLES: '/settings/roles',
  FORBIDDEN: '/403',
} as const;
